name: flutter_widget_test_playground
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm_plex_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans_light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_sans_regular.ttf

  assets:
    - assets/images/chart_setting/area_chart_icon.png
    - assets/images/chart_setting/candle_chart_icon.png
    - assets/images/position_item/volatility_100.png
    - assets/images/position_item/vector.png
    - assets/images/position_item/icon.png
